name: Cbeci frontend production server deploy
on: 
  push:
    branches:
      - master
    paths:
      - 'frontend/*'
jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: CLI commands for build project
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.DEMO_SERVER_HOST }}
        username: cbeci
        port: 22
        envs: SHA
        script_stop: true
        key:  ${{ secrets.CBECI_USER_KEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}
          rm -rf releases/$SHA
          mkdir releases/$SHA
          cd releases/$SHA
          ssh-agent bash -c 'ssh-add /home/cbeci/.ssh/id_rsa_mining_energy_consumption; git clone git@github.com:dektox/mining_energy_consumption.git .'
          git checkout $SHA
          cd frontend
          npm i
          cp ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/.env .env
          npm run generate
          ssh cbeci@${{ secrets.PRODUCTION_SERVER_HOST }} "rm -rf ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA;mkdir -p ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA;"
          scp -r ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA/frontend/dist cbeci@${{ secrets.PRODUCTION_SERVER_HOST }}:${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA
    - uses: actions/checkout@v1
    - name: CLI commands for launch built project on live server
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        username: cbeci
        port: 22
        envs: SHA
        script_stop: true
        key:  ${{ secrets.CBECI_USER_KEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}
          rm -rf actual
          ln -s ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA/dist ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/actual
